import React from "react";
import "@huksley/react-responsive-modal/styles.css";
import { Modal } from "@huksley/react-responsive-modal";

const PrivacyModal = (props) => {
  const [open, setOpen] = React.useState(false);
  const policyText = (
    <p>
      Welcome to Swapy.
      <br />
      Swapy (“us”, “we”, or “our”) operates https://swapy.com/ (hereinafter
      referred to as “Service”).
      <br />
      Our Privacy Policy governs your visit to https://swapy.com/, and explains
      how we collect, safeguard and disclose information that results from your
      use of our Service. We use your data to provide and improve Service. By
      using Service, you agree to the collection and use of information in
      accordance with this policy. Unless otherwise defined in this Privacy
      Policy, the terms used in this Privacy Policy have the same meanings as in
      our Terms and Conditions. Our Terms and Conditions (“Terms”) govern all
      use of our Service and together with the Privacy Policy constitutes your
      agreement with us (“agreement”).
      <br />
      <br />
      <h2>Definitions</h2> <br />
      SERVICE means the https://swapy.com/ website operated by Swapy.
      PERSONAL DATA means data about a living individual who can be identified
      from those data (or from those and other information either in our
      possession or likely to come into our possession). USAGE DATA is data
      collected automatically either generated by the use of Service or from
      Service infrastructure itself (for example, the duration of a page visit).
      COOKIES are small files stored on your device (computer or mobile device).
      DATA CONTROLLER means a natural or legal person who (either alone or
      jointly or in common with other persons) determines the purposes for which
      and the manner in which any personal data are, or are to be, processed.
      For the purpose of this Privacy Policy, we are a Data Controller of your
      data. DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal
      person who processes the data on behalf of the Data Controller. We may use
      the services of various Service Providers in order to process your data
      more effectively. DATA SUBJECT is any living individual who is the subject
      of Personal Data. THE USER is the individual using our Service. The User
      corresponds to the Data Subject, who is the subject of Personal Data.
    </p>
  );
  return (
    <>
      <button className="item1" onClick={() => setOpen(true)}>
        Privacy Policy
      </button>
      <Modal open={open} onClose={() => setOpen(false)} center>
        <h2>Privacy Policy</h2>
        {policyText}
      </Modal>
    </>
  );
};

export default PrivacyModal;







