export const authActions = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
};

export const itemsActions = {
    ADD_ITEM_REQUEST: 'ADD_ITEM_REQUEST',
    ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAILURE: 'ADD_ITEM_FAILURE',
    GET_ITEMS_REQUEST: 'GET_ITEMS_REQUEST',
    GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
    GET_ITEMS_FAILURE: 'GET_ITEMS_FAILURE',
    GET_ITEM_REQUEST: 'GET_ITEM_REQUEST',
    GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
    GET_ITEM_FAILURE: 'GET_ITEM_FAILURE',
    DELETE_ITEM_REQUEST: 'DELETE_ITEM_REQUEST',
    DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
    DELETE_ITEM_FAILURE: 'DELETE_ITEM_FAILURE',
    UPDATE_ITEM_REQUEST: 'UPDATE_ITEM_REQUEST',
    UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
    UPDATE_ITEM_FAILURE: 'UPDATE_ITEM_FAILURE',
};